### ISSUE TITLE
war file and tomcat conf

### ISSUE THREAD

**Issue by adrian-gluu** [GluuFederation/oxEleven#1]
there isn't any war file, how we build this code to package it? also what changes we need to add into that json conf file?

can you clarify that Javier?

**Comment by adrian-gluu** [comment]
also i forgot to mention in linux this path tomcat/conf didn't exist so where you want to place this file?
/var/lib/tomcat6/? (where there?)
or in /etc/tomcat6/? (where there?)

**Comment by qbert2k** [comment]
I have changed the path in README.md to:

$CATALINA_HOME/conf/oxeleven-config.json

war file is located in: https://ox.gluu.org/maven/org/gluu/oxeleven-server
