### ISSUE TITLE
softhsm library in CentOS6 and RHEL6

### ISSUE THREAD

**Issue by adrian-gluu** [GluuFederation/oxEleven#3]
as you doc says we need /usr/local/lib/softhsm/libsofthsm2.so
but in centos 6
we have an old version and in a different path:
[root@localhost ~]# rpm -qa|grep softhsm
softhsm-1.3.5-2.el6.x86_64
[root@localhost ~]# cd /
[root@localhost /]# find . -name libsofthsm.so
./usr/lib64/softhsm/libsofthsm.so
[root@localhost /]#

we can use that version?

**Comment by qbert2k** [comment]
oxEleven works only with SoftHSM v2.x
